FROM tensorflow/tensorflow
RUN apt-get update
RUN apt-get upgrade -y
RUN apt-get install -y  --no-install-recommends \
	cmake \
	libjpeg8-dev \
	libtiff5-dev \
	libjasper-dev \
	libpng12-dev \
	libavcodec-dev \
	libavformat-dev \
	libswscale-dev \
	libv4l-dev \
	libxvidcore-dev \
	libx264-dev \
  	libgtk-3-dev \
	libatlas-base-dev \
	gfortran \
	python2.7-dev \
	python3.5-dev \
	python-opencv \
	python-matplotlib
